numbers: numbers.c
	gcc -c numbers.c; \
	ar -cvq libnumbers.a numbers.o

strings: strings.c
	gcc -c strings.c; \
	ar -cvq libstrings.a strings.o
arrays: arrays.c
	gcc -c arrays.c; \
	ar -cvq libarrays.a arrays.o
